<script>
    try {
        const array= new array(999999999999999999999999999999)
    } catch (error) {
        console.log(error);
        console.log();
        console.log(`예외 이름${error.name}`);
        console.log(`예외 메세지${error.message}`);
    }
</script>